Broke many tests but I do not know why.
David, many tests are failing because of the following error:

Error:  Type uuid does not exist at /usr/local/lib/perl5/site_perl/5.8.7/Class/Meta/Attribute.pm line 407

This happened after I added the version information.  I have searched
through the diffs to figure out what I broken, but I cannot see anything.

* Added version information and tests
* Pod coverage tests now automatically skip aliased classes.
* add_select_widget for Kinetic REST XML generation now accepts named
  parameters.
* Corrected several typos.

If you have any idea whats causing the error, I would love to know what
it is!